spring:
  profiles:
    active: local
  application:
    name: rest-api-example
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:10000/user?useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_bin&characterSetResults=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 600000
      auto-commit: true
      connection-timeout: 10000
      validation-timeout: 10000
      minimum-idle: 10
      pool-name: default
      connection-test-query: select 1
